plugins {
    id 'java'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.1')
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework:spring-webmvc'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
