main:
  datasource:
    url: jdbc:h2:file:.jmix/h2/demo
    username: sa
    password: ""
  liquibase:
    change-log: com/jmifx/demo/liquibase/changelog.xml

jmix:
  core:
    available-locales: en

server:
  port: 8080
