package com.jmifx.codegen.emit;

import com.jmifx.codegen.model.ViewElement;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/** Emits the global registry index listing every view (deterministic order). */
public final class ViewsIndexWriter {

    public String render(List<ViewElement> views) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by jmifx-codegen — DO NOT EDIT\n");
        sb.append("package com.jmifx.generated;\n\n");
        sb.append("import com.jmifx.FxViewRegistry;\n");
        for (ViewElement view : views) {
            sb.append('\n').append("import ").append(view.controllerFqcn()
                    .substring(0, view.controllerFqcn().lastIndexOf('.')))
                    .append('.').append(view.generatedClassName()).append(';');
        }
        sb.append('\n').append('\n');
        sb.append("public final class FxViewsIndex {\n\n");
        sb.append("    public static void registerAll(FxViewRegistry registry) {\n");
        List<ViewElement> sorted = views.stream()
                .sorted(Comparator.comparing(ViewElement::viewId))
                .collect(Collectors.toList());
        for (ViewElement view : sorted) {
            sb.append("        registry.register(\"").append(view.viewId())
                    .append("\", ").append(view.generatedClassName()).append("::new);\n");
        }
        sb.append("    }\n\n");
        sb.append("    private FxViewsIndex() {\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }
}
